server:
  port: 8080
spring:
  application:
    name: runhang-api-gateway
eureka:
  client:
    registerWithEureka: true #是否注册到服务中心
    fetchRegistry: true  #是否拉取服务注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  prefix: /api   #前缀, 这样请求url需要为/api/XXX-service才会匹配到/XXX-service

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
